name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Build serde feature
      run: cargo build --features serde --verbose

    - name: Run tests
      run: cargo test --verbose
    - name: Run test serde feature
      run: cargo test --features serde --verbose
